var files_dup =
[
    [ "Contentes", "df/d1e/md__c_1__a_v_r__drivers__a_v_r__device__drivers.html#autotoc_md1", null ],
    [ "Brief", "df/d1e/md__c_1__a_v_r__drivers__a_v_r__device__drivers.html#autotoc_md2", null ],
    [ "Installtion instructions", "df/d1e/md__c_1__a_v_r__drivers__a_v_r__device__drivers.html#autotoc_md6", null ],
    [ "How to use  ?", "df/d1e/md__c_1__a_v_r__drivers__a_v_r__device__drivers.html#autotoc_md7", null ],
    [ "Copy Rights", "df/d1e/md__c_1__a_v_r__drivers__a_v_r__device__drivers.html#autotoc_md8", null ],
    [ "Bugs", "df/d1e/md__c_1__a_v_r__drivers__a_v_r__device__drivers.html#autotoc_md9", null ],
    [ "Change log", "df/d1e/md__c_1__a_v_r__drivers__a_v_r__device__drivers.html#autotoc_md10", [
      [ "Development", "df/d1e/md__c_1__a_v_r__drivers__a_v_r__device__drivers.html#autotoc_md11", null ]
    ] ],
    [ "Contact informations", "df/d1e/md__c_1__a_v_r__drivers__a_v_r__device__drivers.html#autotoc_md12", null ],
    [ "ADC_config.h", "d0/d51/_a_d_c__config_8h.html", "d0/d51/_a_d_c__config_8h" ],
    [ "ADC_interface.h", "d6/d2f/_a_d_c__interface_8h.html", "d6/d2f/_a_d_c__interface_8h" ],
    [ "ADC_program.c", "d7/d73/_a_d_c__program_8c.html", "d7/d73/_a_d_c__program_8c" ],
    [ "BIT_MATH.h", "d4/deb/_b_i_t___m_a_t_h_8h.html", "d4/deb/_b_i_t___m_a_t_h_8h" ],
    [ "EXTI_interface.h", "df/dec/_e_x_t_i__interface_8h.html", "df/dec/_e_x_t_i__interface_8h" ],
    [ "EXTI_program.c", "d4/d69/_e_x_t_i__program_8c.html", "d4/d69/_e_x_t_i__program_8c" ],
    [ "GPIO_interface.h", "dc/dbd/_g_p_i_o__interface_8h.html", "dc/dbd/_g_p_i_o__interface_8h" ],
    [ "GPIO_program.c", "dd/dd5/_g_p_i_o__program_8c.html", "dd/dd5/_g_p_i_o__program_8c" ],
    [ "I2C_interface.h", "d6/d8c/_i2_c__interface_8h.html", "d6/d8c/_i2_c__interface_8h" ],
    [ "I2C_program.c", "d1/d2e/_i2_c__program_8c.html", "d1/d2e/_i2_c__program_8c" ],
    [ "main.c", "d0/d29/main_8c.html", "d0/d29/main_8c" ],
    [ "Mem_Map32.h", "dc/d02/_mem___map32_8h.html", "dc/d02/_mem___map32_8h" ],
    [ "SPI_config.h", "d9/d8c/_s_p_i__config_8h.html", "d9/d8c/_s_p_i__config_8h" ],
    [ "SPI_interface.h", "dd/dc4/_s_p_i__interface_8h.html", "dd/dc4/_s_p_i__interface_8h" ],
    [ "SPI_program.c", "d8/db9/_s_p_i__program_8c.html", "d8/db9/_s_p_i__program_8c" ],
    [ "STD_TYPES.h", "d1/de4/_s_t_d___t_y_p_e_s_8h.html", "d1/de4/_s_t_d___t_y_p_e_s_8h" ],
    [ "SYSCNTRL_interface.h", "d4/dfc/_s_y_s_c_n_t_r_l__interface_8h.html", "d4/dfc/_s_y_s_c_n_t_r_l__interface_8h" ],
    [ "SYSCNTRL_program.c", "d7/d01/_s_y_s_c_n_t_r_l__program_8c.html", "d7/d01/_s_y_s_c_n_t_r_l__program_8c" ],
    [ "TIMER0_config.h", "d2/de3/_t_i_m_e_r0__config_8h.html", "d2/de3/_t_i_m_e_r0__config_8h" ],
    [ "TIMER0_interface.h", "d6/db6/_t_i_m_e_r0__interface_8h.html", "d6/db6/_t_i_m_e_r0__interface_8h" ],
    [ "TIMER0_program.c", "dd/d7c/_t_i_m_e_r0__program_8c.html", "dd/d7c/_t_i_m_e_r0__program_8c" ],
    [ "USART_config.h", "d8/d0a/_u_s_a_r_t__config_8h.html", "d8/d0a/_u_s_a_r_t__config_8h" ],
    [ "USART_interface.h", "da/d84/_u_s_a_r_t__interface_8h.html", "da/d84/_u_s_a_r_t__interface_8h" ],
    [ "USART_program.c", "d6/d17/_u_s_a_r_t__program_8c.html", "d6/d17/_u_s_a_r_t__program_8c" ],
    [ "WDT_interface.h", "db/d30/_w_d_t__interface_8h.html", "db/d30/_w_d_t__interface_8h" ],
    [ "WDT_program.c", "d0/dbd/_w_d_t__program_8c.html", "d0/dbd/_w_d_t__program_8c" ]
];